/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Route */
        get: operations["list_task_route_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repository-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repository Bindings Route */
        get: operations["list_repository_bindings_route_api_v1_repository_bindings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/from-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task Route */
        post: operations["start_task_route_api_v1_tasks_from_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Route */
        get: operations["get_task_route_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply Route */
        post: operations["reply_route_api_v1_tasks__task_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/outline/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Outline Route */
        post: operations["confirm_outline_route_api_v1_tasks__task_id__outline_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/units/{unit_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Unit Route */
        post: operations["confirm_unit_route_api_v1_tasks__task_id__units__unit_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/revisions/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Revision Route */
        post: operations["approve_revision_route_api_v1_tasks__task_id__revisions_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Route */
        post: operations["finalize_route_api_v1_tasks__task_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Route */
        post: operations["reopen_route_api_v1_tasks__task_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/exports/feishu/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Feishu Export Route */
        post: operations["preview_feishu_export_route_api_v1_tasks__task_id__exports_feishu_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/exports/feishu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Feishu Export Route */
        post: operations["execute_feishu_export_route_api_v1_tasks__task_id__exports_feishu_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports Route */
        get: operations["list_exports_route_api_v1_tasks__task_id__exports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events Route */
        get: operations["events_route_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRevisionRequest */
        ApproveRevisionRequest: {
            /** Document Id */
            document_id: string;
            /** Issue Ids */
            issue_ids: string[];
            /** Unit Ids */
            unit_ids: string[];
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** AvailableActionView */
        AvailableActionView: {
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Expected Task Version */
            expected_task_version: number;
            /** Target Id */
            target_id?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Destructive
             * @default false
             */
            destructive: boolean;
        };
        /** ConfirmOutlineRequest */
        ConfirmOutlineRequest: {
            /** Outline Version */
            outline_version: number;
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** ConfirmUnitRequest */
        ConfirmUnitRequest: {
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** ConflictView */
        ConflictView: {
            /** Conflict Id */
            conflict_id: string;
            /** Subject */
            subject: string;
            /** Description */
            description: string;
            /** Fact Ids */
            fact_ids: string[];
            /** Status */
            status: string;
        };
        /** CoverageItemView */
        CoverageItemView: {
            /** Key */
            key: string;
            /** Description */
            description: string;
            /** Status */
            status: string;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Fact Ids */
            fact_ids: string[];
            /** Unknown Ids */
            unknown_ids: string[];
            /** Conflict Ids */
            conflict_ids: string[];
        };
        /** DocumentView */
        DocumentView: {
            /** Document Id */
            document_id: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Content Hash */
            content_hash: string;
            /** Markdown */
            markdown: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Evidence Id */
            evidence_id: string;
            /** Source Kind */
            source_kind: string;
            /** Source Id */
            source_id: string;
            /** Source Version */
            source_version: string;
            /** Locator */
            locator: {
                [key: string]: unknown;
            };
            /** Excerpt */
            excerpt: string;
            /** Content Hash */
            content_hash: string;
            /** Extraction Method */
            extraction_method: string;
            /** Redaction Applied */
            redaction_applied: boolean;
        };
        /** ExecuteExportRequest */
        ExecuteExportRequest: {
            /** Intent Id */
            intent_id: string;
            /** Confirmation Token */
            confirmation_token: string;
            mode: components["schemas"]["ExportMode"];
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** ExportListResponse */
        ExportListResponse: {
            /** Items */
            items: components["schemas"]["ExportRunView"][];
        };
        /**
         * ExportMode
         * @enum {string}
         */
        ExportMode: "CREATE" | "OVERWRITE_BOUND";
        /** ExportPreviewRequest */
        ExportPreviewRequest: {
            mode: components["schemas"]["ExportMode"];
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** ExportPreviewView */
        ExportPreviewView: {
            /** Intent Id */
            intent_id: string;
            /** Confirmation Token */
            confirmation_token: string;
            /** Mode */
            mode: string;
            /** Title */
            title: string;
            /** Task Version */
            task_version: number;
            /** Document Version */
            document_version: number;
            /** Content Hash */
            content_hash: string;
            /** Unresolved Items */
            unresolved_items: string[];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Bound Title */
            bound_title?: string | null;
            /** Bound Safe Url */
            bound_safe_url?: string | null;
        };
        /** ExportRunView */
        ExportRunView: {
            /** Export Run Id */
            export_run_id: string;
            /** Intent Id */
            intent_id: string;
            /** Mode */
            mode: string;
            /** Task Version */
            task_version: number;
            /** Document Version */
            document_version: number;
            /** Content Hash */
            content_hash: string;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Binding Id */
            binding_id?: string | null;
            /** Safe Url */
            safe_url?: string | null;
            /** Display Title */
            display_title?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Retryable */
            retryable: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** FactView */
        FactView: {
            /** Fact Id */
            fact_id: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Value */
            value: unknown;
            /** Fact Scope */
            fact_scope: string;
            /** Fact Type */
            fact_type: string;
            /** Verification Status */
            verification_status: string;
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** FinalizeRequest */
        FinalizeRequest: {
            /** Document Id */
            document_id: string;
            /** Content Hash */
            content_hash: string;
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** GroundingView */
        GroundingView: {
            /** Grounding Run Id */
            grounding_run_id: string;
            /** Unit Id */
            unit_id: string;
            /** Status */
            status: string;
            /** Confirmable */
            confirmable: boolean;
            /** Issues */
            issues: string[];
            /** Reference Count */
            reference_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvestigationStepView */
        InvestigationStepView: {
            /** Sequence */
            sequence: number;
            /** Iteration */
            iteration: number;
            /** Step Type */
            step_type: string;
            /** Status */
            status: string;
            /** Public Summary */
            public_summary: string;
        };
        /** InvestigationView */
        InvestigationView: {
            /** Investigation Id */
            investigation_id: string;
            /** Information Need Id */
            information_need_id: string;
            /** Unit Id */
            unit_id?: string | null;
            /** Question */
            question: string;
            /** Requiredness */
            requiredness: string;
            /** Source Types */
            source_types: string[];
            /** Status */
            status: string;
            /** Stop Reason */
            stop_reason?: string | null;
            /** Coverage */
            coverage: components["schemas"]["CoverageItemView"][];
            /** Steps */
            steps: components["schemas"]["InvestigationStepView"][];
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCallView"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceView"][];
            /** Facts */
            facts: components["schemas"]["FactView"][];
            /** Unknowns */
            unknowns: components["schemas"]["UnknownView"][];
            /** Conflicts */
            conflicts: components["schemas"]["ConflictView"][];
        };
        /** MessageView */
        MessageView: {
            /** Message Id */
            message_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "agent" | "system";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OutlineNodeView */
        OutlineNodeView: {
            /** Node Id */
            node_id: string;
            /** Sequence */
            sequence: number;
            /** Title */
            title: string;
            /** Purpose */
            purpose: string;
            /** Complexity */
            complexity: string;
            /** Parent Id */
            parent_id?: string | null;
            /** Level */
            level: number;
        };
        /** OutlineView */
        OutlineView: {
            /** Outline Id */
            outline_id: string;
            /** Version */
            version: number;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Nodes */
            nodes: components["schemas"]["OutlineNodeView"][];
            /** Units */
            units: components["schemas"]["UnitView"][];
        };
        /** QualityIssueView */
        QualityIssueView: {
            /** Issue Id */
            issue_id: string;
            /** Issue Type */
            issue_type: string;
            /** Severity */
            severity: string;
            /** Description */
            description: string;
            /** Suggested Resolution */
            suggested_resolution: string;
            /** Affected Unit Ids */
            affected_unit_ids: string[];
        };
        /** QualityView */
        QualityView: {
            /** Quality Run Id */
            quality_run_id: string;
            /** Scope */
            scope: string;
            /** Scope Id */
            scope_id: string;
            /** Confirmable */
            confirmable: boolean;
            /** Issues */
            issues: components["schemas"]["QualityIssueView"][];
        };
        /** ReopenRequest */
        ReopenRequest: {
            /** Unit Ids */
            unit_ids: string[];
            /** Reason */
            reason: string;
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** ReplyRequest */
        ReplyRequest: {
            /** Message */
            message: string;
            /** Expected Task Version */
            expected_task_version: number;
        };
        /** RepositoryBindingListResponse */
        RepositoryBindingListResponse: {
            /** Items */
            items: components["schemas"]["RepositoryBindingView"][];
        };
        /** RepositoryBindingView */
        RepositoryBindingView: {
            /** Repository Id */
            repository_id: string;
            /** Provider */
            provider: string;
            /** Display Name */
            display_name: string;
            /** Default Revision */
            default_revision: string;
            /** Allowed Prefix */
            allowed_prefix: string;
        };
        /** RunView */
        RunView: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /** StartTaskRequest */
        StartTaskRequest: {
            /** Message */
            message: string;
        };
        /** TaskDetailResponse */
        TaskDetailResponse: {
            task: components["schemas"]["TaskSummaryView"];
            run: components["schemas"]["RunView"];
            /** Brief */
            brief?: {
                [key: string]: unknown;
            } | null;
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            outline?: components["schemas"]["OutlineView"] | null;
            /** Investigations */
            investigations: components["schemas"]["InvestigationView"][];
            /** Grounding */
            grounding: components["schemas"]["GroundingView"][];
            /** Quality */
            quality: components["schemas"]["QualityView"][];
            document?: components["schemas"]["DocumentView"] | null;
            /** Available Actions */
            available_actions: components["schemas"]["AvailableActionView"][];
            /** Latest Event Sequence */
            latest_event_sequence: number;
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Items */
            items: components["schemas"]["TaskSummaryView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TaskSummaryView */
        TaskSummaryView: {
            /** Task Id */
            task_id: string;
            /** Title */
            title: string;
            /** Task Status */
            task_status: string;
            /** Run Status */
            run_status?: string | null;
            /** Display Status */
            display_status: string;
            /** Version */
            version: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Current Unit Sequence */
            current_unit_sequence?: number | null;
            /** Attention Required */
            attention_required: boolean;
        };
        /** ToolCallView */
        ToolCallView: {
            /** Tool Call Id */
            tool_call_id: string;
            /** Tool Id */
            tool_id: string;
            /** Status */
            status: string;
            /** Purpose */
            purpose: string;
            /** Public Summary */
            public_summary: string;
            /** Error Code */
            error_code?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
        };
        /** UnitView */
        UnitView: {
            /** Unit Id */
            unit_id: string;
            /** Sequence */
            sequence: number;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Node Ids */
            node_ids: string[];
            /** Depends On Unit Ids */
            depends_on_unit_ids: string[];
            /** Content */
            content?: string | null;
            /** Content Hash */
            content_hash?: string | null;
        };
        /** UnknownView */
        UnknownView: {
            /** Unknown Id */
            unknown_id: string;
            /** Statement */
            statement: string;
            /** Reason */
            reason: string;
            /** Severity */
            severity: string;
            /** Resolution Type */
            resolution_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_task_route_api_v1_tasks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repository_bindings_route_api_v1_repository_bindings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryBindingListResponse"];
                };
            };
        };
    };
    start_task_route_api_v1_tasks_from_message_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_route_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply_route_api_v1_tasks__task_id__messages_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_outline_route_api_v1_tasks__task_id__outline_confirm_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmOutlineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_unit_route_api_v1_tasks__task_id__units__unit_id__confirm_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmUnitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_revision_route_api_v1_tasks__task_id__revisions_approve_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_route_api_v1_tasks__task_id__finalize_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_route_api_v1_tasks__task_id__reopen_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_feishu_export_route_api_v1_tasks__task_id__exports_feishu_preview_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_feishu_export_route_api_v1_tasks__task_id__exports_feishu_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exports_route_api_v1_tasks__task_id__exports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_route_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: {
                after_sequence?: number;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
