# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import agent_execution_pb2 as agent_dot_v1_dot_agent__execution__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_execution_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentExecutionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireRun = channel.unary_unary(
                '/agent.v1.AgentExecutionService/AcquireRun',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.AcquireRunRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.AcquireRunResponse.FromString,
                _registered_method=True)
        self.GetRunContext = channel.unary_unary(
                '/agent.v1.AgentExecutionService/GetRunContext',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.GetRunContextRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.GetRunContextResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/agent.v1.AgentExecutionService/Heartbeat',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RecordModelAttempt = channel.unary_unary(
                '/agent.v1.AgentExecutionService/RecordModelAttempt',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptResponse.FromString,
                _registered_method=True)
        self.AppendEvidence = channel.unary_unary(
                '/agent.v1.AgentExecutionService/AppendEvidence',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/agent.v1.AgentExecutionService/SaveCheckpoint',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.SubmitDraft = channel.unary_unary(
                '/agent.v1.AgentExecutionService/SubmitDraft',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.SubmitDraftRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.SubmitDraftResponse.FromString,
                _registered_method=True)
        self.CompleteRun = channel.unary_unary(
                '/agent.v1.AgentExecutionService/CompleteRun',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.CompleteRunRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.CompleteRunResponse.FromString,
                _registered_method=True)
        self.FailRun = channel.unary_unary(
                '/agent.v1.AgentExecutionService/FailRun',
                request_serializer=agent_dot_v1_dot_agent__execution__pb2.FailRunRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__execution__pb2.FailRunResponse.FromString,
                _registered_method=True)


class AgentExecutionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AcquireRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordModelAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitDraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentExecutionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireRun': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireRun,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.AcquireRunRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.AcquireRunResponse.SerializeToString,
            ),
            'GetRunContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunContext,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.GetRunContextRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.GetRunContextResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.HeartbeatRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RecordModelAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordModelAttempt,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptResponse.SerializeToString,
            ),
            'AppendEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEvidence,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'SubmitDraft': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitDraft,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.SubmitDraftRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.SubmitDraftResponse.SerializeToString,
            ),
            'CompleteRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRun,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.CompleteRunRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.CompleteRunResponse.SerializeToString,
            ),
            'FailRun': grpc.unary_unary_rpc_method_handler(
                    servicer.FailRun,
                    request_deserializer=agent_dot_v1_dot_agent__execution__pb2.FailRunRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__execution__pb2.FailRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentExecutionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentExecutionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentExecutionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquireRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/AcquireRun',
            agent_dot_v1_dot_agent__execution__pb2.AcquireRunRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.AcquireRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/GetRunContext',
            agent_dot_v1_dot_agent__execution__pb2.GetRunContextRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.GetRunContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/Heartbeat',
            agent_dot_v1_dot_agent__execution__pb2.HeartbeatRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordModelAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/RecordModelAttempt',
            agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.RecordModelAttemptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/AppendEvidence',
            agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.AppendEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/SaveCheckpoint',
            agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitDraft(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/SubmitDraft',
            agent_dot_v1_dot_agent__execution__pb2.SubmitDraftRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.SubmitDraftResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/CompleteRun',
            agent_dot_v1_dot_agent__execution__pb2.CompleteRunRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.CompleteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentExecutionService/FailRun',
            agent_dot_v1_dot_agent__execution__pb2.FailRunRequest.SerializeToString,
            agent_dot_v1_dot_agent__execution__pb2.FailRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
