# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import agent_worker_pb2 as agent_dot_v1_dot_agent__worker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/agent_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentWorkerServiceStub:
    """AgentWorkerService is the Go -> Python execution contract. Python owns the
    model/tool loop; Go remains the owner of all durable run state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteRun = channel.unary_stream(
                '/agent.v1.AgentWorkerService/ExecuteRun',
                request_serializer=agent_dot_v1_dot_agent__worker__pb2.ExecuteRunRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__worker__pb2.ExecuteRunResponse.FromString,
                _registered_method=True)
        self.AcknowledgeEvent = channel.unary_unary(
                '/agent.v1.AgentWorkerService/AcknowledgeEvent',
                request_serializer=agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/agent.v1.AgentWorkerService/CancelRun',
                request_serializer=agent_dot_v1_dot_agent__worker__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__worker__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agent.v1.AgentWorkerService/Health',
                request_serializer=agent_dot_v1_dot_agent__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_agent__worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentWorkerServiceServicer:
    """AgentWorkerService is the Go -> Python execution contract. Python owns the
    model/tool loop; Go remains the owner of all durable run state.
    """

    def ExecuteRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcknowledgeEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteRun': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteRun,
                    request_deserializer=agent_dot_v1_dot_agent__worker__pb2.ExecuteRunRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__worker__pb2.ExecuteRunResponse.SerializeToString,
            ),
            'AcknowledgeEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeEvent,
                    request_deserializer=agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=agent_dot_v1_dot_agent__worker__pb2.CancelRunRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__worker__pb2.CancelRunResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent_dot_v1_dot_agent__worker__pb2.HealthRequest.FromString,
                    response_serializer=agent_dot_v1_dot_agent__worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentWorkerService:
    """AgentWorkerService is the Go -> Python execution contract. Python owns the
    model/tool loop; Go remains the owner of all durable run state.
    """

    @staticmethod
    def ExecuteRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.v1.AgentWorkerService/ExecuteRun',
            agent_dot_v1_dot_agent__worker__pb2.ExecuteRunRequest.SerializeToString,
            agent_dot_v1_dot_agent__worker__pb2.ExecuteRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcknowledgeEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentWorkerService/AcknowledgeEvent',
            agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventRequest.SerializeToString,
            agent_dot_v1_dot_agent__worker__pb2.AcknowledgeEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentWorkerService/CancelRun',
            agent_dot_v1_dot_agent__worker__pb2.CancelRunRequest.SerializeToString,
            agent_dot_v1_dot_agent__worker__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentWorkerService/Health',
            agent_dot_v1_dot_agent__worker__pb2.HealthRequest.SerializeToString,
            agent_dot_v1_dot_agent__worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
