# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agent.v1 import capability_gateway_pb2 as agent_dot_v1_dot_capability__gateway__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/capability_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityGatewayServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadRepositoryTree = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/ReadRepositoryTree',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeResponse.FromString,
                _registered_method=True)
        self.ReadRepositoryFile = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/ReadRepositoryFile',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileResponse.FromString,
                _registered_method=True)
        self.SearchRepository = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/SearchRepository',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryResponse.FromString,
                _registered_method=True)
        self.SearchPrdCatalog = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/SearchPrdCatalog',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogResponse.FromString,
                _registered_method=True)
        self.FetchPrdSections = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/FetchPrdSections',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsResponse.FromString,
                _registered_method=True)
        self.CreateExportIntent = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/CreateExportIntent',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentResponse.FromString,
                _registered_method=True)
        self.SearchProjectMemory = channel.unary_unary(
                '/agent.v1.CapabilityGatewayService/SearchProjectMemory',
                request_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryResponse.FromString,
                _registered_method=True)


class CapabilityGatewayServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReadRepositoryTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadRepositoryFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPrdCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchPrdSections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateExportIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchProjectMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadRepositoryTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRepositoryTree,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeResponse.SerializeToString,
            ),
            'ReadRepositoryFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadRepositoryFile,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileResponse.SerializeToString,
            ),
            'SearchRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRepository,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryResponse.SerializeToString,
            ),
            'SearchPrdCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchPrdCatalog,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogResponse.SerializeToString,
            ),
            'FetchPrdSections': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchPrdSections,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsResponse.SerializeToString,
            ),
            'CreateExportIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateExportIntent,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentResponse.SerializeToString,
            ),
            'SearchProjectMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProjectMemory,
                    request_deserializer=agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryRequest.FromString,
                    response_serializer=agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.CapabilityGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.CapabilityGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityGatewayService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadRepositoryTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/ReadRepositoryTree',
            agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadRepositoryFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/ReadRepositoryFile',
            agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.ReadRepositoryFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/SearchRepository',
            agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.SearchRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchPrdCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/SearchPrdCatalog',
            agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.SearchPrdCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchPrdSections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/FetchPrdSections',
            agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.FetchPrdSectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateExportIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/CreateExportIntent',
            agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.CreateExportIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchProjectMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.CapabilityGatewayService/SearchProjectMemory',
            agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryRequest.SerializeToString,
            agent_dot_v1_dot_capability__gateway__pb2.SearchProjectMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
