from __future__ import annotations

from enum import StrEnum


class TaskStatus(StrEnum):
    DRAFT = "DRAFT"
    CLARIFYING = "CLARIFYING"
    OUTLINE_REVIEW = "OUTLINE_REVIEW"
    GENERATING = "GENERATING"
    FINAL_REVIEW = "FINAL_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"
    DELETING = "DELETING"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_USER = "WAITING_USER"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"


class OutlineStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    SUPERSEDED = "SUPERSEDED"


class UnitStatus(StrEnum):
    PENDING = "PENDING"
    PREPARING = "PREPARING"
    INVESTIGATING = "INVESTIGATING"
    GENERATING = "GENERATING"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    HUMAN_INPUT_REQUIRED = "HUMAN_INPUT_REQUIRED"
    SUPERSEDED = "SUPERSEDED"
    FAILED = "FAILED"


class SectionStatus(StrEnum):
    DRAFT = "DRAFT"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    INVALIDATED = "INVALIDATED"
    SUPERSEDED = "SUPERSEDED"


class DocumentStatus(StrEnum):
    CHECKING = "CHECKING"
    FINAL_REVIEW = "FINAL_REVIEW"
    CONFIRMED = "CONFIRMED"
    SUPERSEDED = "SUPERSEDED"


class Complexity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


ACTIVE_RUN_STATUSES = frozenset(
    {RunStatus.QUEUED, RunStatus.RUNNING, RunStatus.WAITING_USER}
)
